<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "restaurant_am_vl"
 *
 * Auto generated by Extension Builder 2020-06-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Restaurant AM VL',
    'description' => 'Carte de restaurant',
    'category' => 'plugin',
    'author' => 'Alban MAYUNGA, Victor LEFRANCOIS',
    'author_email' => 'albanmayunga01@gmail.com, lefrancois.victor@hotmail.fr',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
